### ISSUE TITLE
Accept predicate with wildcard not allowed

### ISSUE THREAD

**Issue by ltvolks** [Pylons/pyramid#1407]
The [docs](http://docs.pylonsproject.org/projects/pyramid/en/latest/api/config.html) for the `accept` predicate state that wildcards are allowed, but due to the way the 'offer' is checked in WebOb, an `accept` predicate with any wildcard component will fail: 

`ValueError: The application should offer specific types, got 'text/*'`

Here's a simple example:

```python
from wsgiref.simple_server import make_server
from pyramid.config import Configurator
from pyramid.response import Response


def index(request):
    return Response("Index")

if __name__ == '__main__':
    config = Configurator()
    config.add_route('index', path='/')
    config.add_view(index, route_name='index', accept='text/*')
    app = config.make_wsgi_app()
    server = make_server('0.0.0.0', 8080, app)
    server.serve_forever()
```

```python
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/pyenv/test-accept/lib/python2.7/site-packages/pyramid/router.py", line 242, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/pyenv/test-accept/lib/python2.7/site-packages/pyramid/router.py", line 217, in invoke_subrequest
    response = handle_request(request)
  File "/pyenv/test-accept/lib/python2.7/site-packages/pyramid/tweens.py", line 46, in excview_tween
    response = view_callable(exc, request)
  File "/pyenv/test-accept/lib/python2.7/site-packages/pyramid/config/views.py", line 329, in attr_view
    return view(context, request)
  File "/pyenv/test-accept/lib/python2.7/site-packages/pyramid/config/views.py", line 300, in predicate_wrapper
    if not predicate(context, request):
  File "/pyenv/test-accept/lib/python2.7/site-packages/pyramid/config/predicates.py", line 136, in __call__
    return self.val in request.accept
  File "/pyenv/test-accept/lib/python2.7/site-packages/webob/acceptparse.py", line 120, in __contains__
    if self._match(mask, offer):
  File "/pyenv/test-accept/lib/python2.7/site-packages/webob/acceptparse.py", line 303, in _match
    _check_offer(offer)
  File "/pyenv/test-accept/lib/python2.7/site-packages/webob/acceptparse.py", line 320, in _check_offer
    raise ValueError("The application should offer specific types, got %r" % offer)
ValueError: The application should offer specific types, got 'text/*'
```

**Comment by bertjwregeer** [comment]
This has now been fixed in WebOb using the patch provided by @ltvolks.

**Comment by mmerickel** [comment]
Looks like this will be in webob 1.6.
