### ISSUE TITLE
Convert non-string to string if passed to remember()

### ISSUE THREAD

**Issue by rightaway** [Pylons/pyramid#1530]
I use UUID objects for user IDs, and when I pass it into remember() I get this error `can't concat bytes to UUID`. I need to do `remember(request, str(user.id))` for it to work. Would it make sense for the function to convert any non-string to a string if passed in as the user ID?

```
...
    headers = remember(request, user.id)
  File "/home/a/.virtualenvs/a/lib/python3.4/site-packages/pyramid-1.5.1-py3.4.egg/pyramid/security.py", line 145, in remember
    return policy.remember(request, principal, **kw)
  File "/home/a/.virtualenvs/a/lib/python3.4/site-packages/pyramid-1.5.1-py3.4.egg/pyramid/authentication.py", line 663, in remember
    return self.cookie.remember(request, principal, **kw)
  File "/home/a/.virtualenvs/a/lib/python3.4/site-packages/pyramid-1.5.1-py3.4.egg/pyramid/authentication.py", line 1024, in remember
    cookie_value = ticket.cookie_value()
  File "/home/a/.virtualenvs/a/lib/python3.4/site-packages/pyramid-1.5.1-py3.4.egg/pyramid/authentication.py", line 718, in cookie_value
    v = '%s%08x%s!' % (self.digest(), int(self.time),
  File "/home/a/.virtualenvs/a/lib/python3.4/site-packages/pyramid-1.5.1-py3.4.egg/pyramid/authentication.py", line 715, in digest
    self.user_data, self.hashalg)
  File "/home/a/.virtualenvs/a/lib/python3.4/site-packages/pyramid-1.5.1-py3.4.egg/pyramid/authentication.py", line 794, in calculate_digest
    tokens + b'\0' + user_data)
TypeError: can't concat bytes to UUID
```

**Comment by bertjwregeer** [comment]
I would be a -1 on this. There may be a good reason for the object you are passing to remember() to stay an object, especially if you have a custom authentication policy in place that does know how to handle that.

One could argue that the authtkt implementation should get fixed to automatically convert things to string, but at the same time I would say that if I ask it to remember a UUID and next reload I get back a string instead, it isn't the same thing. Honestly I would subclass authtkt and make sure it handles UUID's correctly for my application.

**Comment by mmerickel** [comment]
I'm also -1 on this. The auth_tkt already handles a few types including int and str but it's really up to the policy and I wouldn't expect arbitrary policies to handle anything more than this. If we were to extend it, I would expect it to be something at the pyramid-level instead of the policy level that did this serialization to avoid adding tons of complexity to every policy (`config.set_userid_serializer(...)`). Since we aren't, and don't see a need for that at this point, you'll need to just fix your policy to deal with this (which is honestly very easy).

https://github.com/Pylons/pyramid/blob/64f9cfaf331310cf54285c49d705098aa3d07944/pyramid/authentication.py#L829

**Comment by rmeno** [comment]
Hello,
I get the same error if I pass a str or int to remember(). Code and full traceback below. 

```
@view_config(
        route_name='login',
        renderer='myproj:templates/auth/login.jinja2',
    )
    def login(self):
        message = ''
        email = ''
        self.log.info(self.request.method)
        if self.request.method == 'POST' and 'form.submitted' in self.request.POST:
            email = self.request.POST['email']
            password = self.request.POST['password']
            user = self.request.dbsession.query(User).filter_by(email=email).first()
            self.log.info('login_POST.user: {0} : {1}'.format(user, type(user)))
            if user is not None and user.check_password(password):
                user_id = user.user_id
                self.log.info(
                    'login_POST.userid: {0}, type: {1}'.format(user_id, type(user_id)))
                next_url = self.request.route_url('home')
                self.log.info('login_POST.next_url: {0}'.format(next_url,))
                headers = remember(self.request, user.user_id)
                return HTTPFound(location=next_url, headers=headers)
            else:
                message = 'Failed login'
        

        return dict(
            message=message,
            url=self.request.route_url('login'),
            email=email,
        )

```


```
2018-02-14 13:25:22,547 INFO  [views.auth:46][waitress] login_POST.userid: 5, type: <class 'int'>
2018-02-14 13:25:22,547 INFO  [views.auth:48][waitress] login_POST.next_url: http://localhost:6543/
2018-02-14 13:25:22,548 INFO  [sqlalchemy.engine.base.Engine:702][waitress] ROLLBACK
2018-02-14 13:25:22,550 ERROR [pyramid_debugtoolbar:267][waitress] Uncaught Exception at http://localhost:6543/login
traceback url: http://localhost:6543/_debug_toolbar/313430373134353837373135343536/exception
Traceback (most recent call last):
  File "/lib/python3.5/site-packages/pyramid/tweens.py", line 12, in _error_handler
    response = request.invoke_exception_view(exc_info)
  File "/lib/python3.5/site-packages/pyramid/view.py", line 756, in invoke_exception_view
    raise HTTPNotFound
pyramid.httpexceptions.HTTPNotFound: The resource could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lib/python3.5/site-packages/pyramid_debugtoolbar/toolbar.py", line 247, in toolbar_tween
    response = _handler(request)
  File "/lib/python3.5/site-packages/pyramid_debugtoolbar/panels/performance.py", line 58, in resource_timer_handler
    result = handler(request)
  File "/lib/python3.5/site-packages/pyramid_tm/__init__.py", line 171, in tm_tween
    reraise(*exc_info)
  File "lib/python3.5/site-packages/pyramid_tm/compat.py", line 36, in reraise
    raise value
  File "lib/python3.5/site-packages/pyramid_tm/__init__.py", line 136, in tm_tween
    response = handler(request)
  File "/lib/python3.5/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = _error_handler(request, exc)
  File "/lib/python3.5/site-packages/pyramid/tweens.py", line 16, in _error_handler
    reraise(*exc_info)
  File "/lib/python3.5/site-packages/pyramid/compat.py", line 148, in reraise
    raise value
  File "/lib/python3.5/site-packages/pyramid/tweens.py", line 39, in excview_tween
    response = handler(request)
  File "/lib/python3.5/site-packages/pyramid/router.py", line 156, in handle_request
    view_name
  File "/lib/python3.5/site-packages/pyramid/view.py", line 642, in _call_view
    response = view_callable(context, request)
  File "/lib/python3.5/site-packages/pyramid/viewderivers.py", line 439, in rendered_view
    result = view(context, request)
  File "/lib/python3.5/site-packages/pyramid/viewderivers.py", line 124, in _class_requestonly_view
    response = getattr(inst, attr)()
  File "/views/auth.py", line 49, in login
    headers = remember(self.request, user.user_id)
  File "/lib/python3.5/site-packages/pyramid/security.py", line 167, in remember
    return policy.remember(request, userid, **kw)
  File "/lib/python3.5/site-packages/pyramid/authentication.py", line 621, in remember
    return self.cookie.remember(request, userid, **kw)
  File "/lib/python3.5/site-packages/pyramid/authentication.py", line 992, in remember
    cookie_value = ticket.cookie_value()
  File "/lib/python3.5/site-packages/pyramid/authentication.py", line 676, in cookie_value
    v = '%s%08x%s!' % (self.digest(), int(self.time),
  File "lib/python3.5/site-packages/pyramid/authentication.py", line 673, in digest
    self.user_data, self.hashalg)
  File "/lib/python3.5/site-packages/pyramid/authentication.py", line 752, in calculate_digest
    tokens + b'\0' + user_data)
TypeError: can't concat bytes to list
```
