### ISSUE TITLE
NameError: name '__cache_***' exception when using metal:define-macro in a template

### ISSUE THREAD

**Issue by mattpepin** [Pylons/pyramid#1572]
Hi,

I'm running into a weird issue with Pyramid 1.5.2. When I try to use variables inside a macro, I get a NameError exception. Here's how to reproduce.

1 - Create a virtualenv and install pyramid
2 - pcreate -t starter test
3 - Edit views.py with the following:
from pyramid.view import view_config
from pyramid.renderers import get_renderer
@view_config(route_name='home', renderer='templates/mytemplate2.pt')
def my_view(request):
    base = get_renderer('templates/mytemplate.pt').implementation().macros['base']
    return {'project': 'test', 'base': base}
4 - Add metal:define-macro="base" to head tag and add metal:define-slot="content" to the body tag in mytemplate.pt
5 - Create mytemplate2.pt with the following content:
[html metal:use-macro="base">
[body metal:fill-slot="content" metal:define-macro="othermacro">
    [div tal:content="project">[/div>
[/body>
[/html>
6 - python setup.py develop
7 - pserve --reload development.ini
8 - Observe the exception

If you remove the metal:define-macro in mytemplate2.pt, it works fine.

***EDIT***: Sorry I had to tweak the HTML in mytemplate2.pt since it was filtered out.

**Comment by mmerickel** [comment]
This issue is gonna belong in pyramid_chameleon[1] or chameleon[2]. It'd certainly help if you pasted a stacktrace.

[1] https://github.com/Pylons/pyramid_chameleon
[2] https://github.com/malthe/chameleon

**Comment by mattpepin** [comment]
Here's the stacktrace:

Traceback (most recent call last):
  File "/home/matt/temp/test/lib/python3.4/site-packages/pyramid_debugtoolbar-2.3-py3.4.egg/pyramid_debugtoolbar/toolbar.py", line 178, in toolbar_tween
    response = _handler(request)
  File "/home/matt/temp/test/lib/python3.4/site-packages/pyramid_debugtoolbar-2.3-py3.4.egg/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/matt/temp/test/lib/python3.4/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/matt/temp/test/lib/python3.4/site-packages/pyramid/router.py", line 163, in handle_request
    response = view_callable(context, request)
  File "/home/matt/temp/test/lib/python3.4/site-packages/pyramid/config/views.py", line 377, in rendered_view
    context)
  File "/home/matt/temp/test/lib/python3.4/site-packages/pyramid/renderers.py", line 418, in render_view
    return self.render_to_response(response, system, request=request)
  File "/home/matt/temp/test/lib/python3.4/site-packages/pyramid/renderers.py", line 441, in render_to_response
    result = self.render(value, system_values, request=request)
  File "/home/matt/temp/test/lib/python3.4/site-packages/pyramid/renderers.py", line 437, in render
    result = renderer(value, system_values)
  File "/home/matt/temp/test/lib/python3.4/site-packages/pyramid_chameleon-0.3-py3.4.egg/pyramid_chameleon/zpt.py", line 47, in __call__
    result = self.template(**system)
  File "/home/matt/temp/test/lib/python3.4/site-packages/Chameleon-2.22-py3.4.egg/chameleon/template.py", line 124, in __call__
    return self.render(**kwargs)
  File "/home/matt/temp/test/lib/python3.4/site-packages/Chameleon-2.22-py3.4.egg/chameleon/zpt/template.py", line 258, in render
    return super(PageTemplate, self).render(**vars)
  File "/home/matt/temp/test/lib/python3.4/site-packages/Chameleon-2.22-py3.4.egg/chameleon/template.py", line 171, in render
    self._render(stream, econtext, rcontext)
  File "mytemplate2_9904d3b9fef68714501148c84218e420.py", line 237, in render
  File "mytemplate_0eb9088fdc4773afff3c15d6943f8401.py", line 736, in render_base
  File "mytemplate2_9904d3b9fef68714501148c84218e420.py", line 215, in __fill_content
NameError: name '__cache_139911775700696' is not defined

**Comment by mmerickel** [comment]
I'd guess you want to redirect this issue to @malthe and the chameleon repo.
