### ISSUE TITLE
Problems with 1.5.3 and starting with CentOS 7 startd/systemctl

### ISSUE THREAD

**Issue by Atman50** [Pylons/pyramid#1594]
'm not sure where to report this, but we start our pyramid project using systemd on CentOS7 - the first patch ( https://github.com/Pylons/pyramid/pull/1577) causes a traceback when run with no terminal at all:

Traceback (most recent call last):
File "/opt/clearsky/bin/pserve", line 9, in <module>
load_entry_point('pyramid==1.5.3', 'console_scripts', 'pserve')()
File "/opt/clearsky/lib/python2.7/site-packages/pyramid-1.5.3-py2.7.egg/pyramid/scripts/pserve.py", line 58, in main return command.run()
File "/opt/clearsky/lib/python2.7/site-packages/pyramid-1.5.3-py2.7.egg/pyramid/scripts/pserve.py", line 226, in run install_reloader(int(self.options.reload_interval), [app_spec])
File "/opt/clearsky/lib/python2.7/site-packages/pyramid-1.5.3-py2.7.egg/pyramid/scripts/pserve.py", line 734, in install_reloader ensure_echo_on()
File "/opt/clearsky/lib/python2.7/site-packages/pyramid-1.5.3-py2.7.egg/pyramid/scripts/pserve.py", line 720, in ensure_echo_on attr_list = termios.tcgetattr(fd)

Anyone else?

Thanks,
-Adam

**Comment by davisagli** [comment]
Does the fix in pyramid 1.5.4 solve the issue?

**Comment by Atman50** [comment]
Yes. It works with 1.5.4.
Thanks!
-Adam

**Comment by Atman50** [comment]
1.5.4 works correctly. Closing.
