### ISSUE TITLE
python 3.4 Error

### ISSUE THREAD

**Issue by cyprusglobe** [Pylons/pyramid#1898]
@mcdonc 
```
switched my code from python 2.7.10 to 3.4.3 now im getting this error


Traceback (most recent call last):
  File "/Users/koder/.virtualenvs/marketapi/bin/pserve", line 9, in <module>
    load_entry_point('pyramid==1.5.7', 'console_scripts', 'pserve')()
  File "/Users/koder/.virtualenvs/marketapi/lib/python3.4/site-packages/pyramid/scripts/pserve.py", line 58, in main
    return command.run()
  File "/Users/koder/.virtualenvs/marketapi/lib/python3.4/site-packages/pyramid/scripts/pserve.py", line 328, in run
    global_conf=vars)
  File "/Users/koder/.virtualenvs/marketapi/lib/python3.4/site-packages/pyramid/scripts/pserve.py", line 363, in loadapp
    return loadapp(app_spec, name=name, relative_to=relative_to, **kw)
  File "/Users/koder/.virtualenvs/marketapi/lib/python3.4/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/Users/koder/.virtualenvs/marketapi/lib/python3.4/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
    return context.create()
  File "/Users/koder/.virtualenvs/marketapi/lib/python3.4/site-packages/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/Users/koder/.virtualenvs/marketapi/lib/python3.4/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/Users/koder/.virtualenvs/marketapi/lib/python3.4/site-packages/paste/deploy/util.py", line 58, in fix_call
    reraise(*exc_info)
  File "/Users/koder/.virtualenvs/marketapi/lib/python3.4/site-packages/paste/deploy/compat.py", line 32, in reraise
    raise e.with_traceback(tb)
  File "/Users/koder/.virtualenvs/marketapi/lib/python3.4/site-packages/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/Users/koder/.virtualenvs/marketapi/marketapi/marketapi/__init__.py", line 131, in main
    return config.make_wsgi_app()
  File "/Users/koder/.virtualenvs/marketapi/lib/python3.4/site-packages/pyramid/config/__init__.py", line 939, in make_wsgi_app
    self.commit()
  File "/Users/koder/.virtualenvs/marketapi/lib/python3.4/site-packages/pyramid/config/__init__.py", line 610, in commit
    self.action_state.execute_actions(introspector=self.introspector)
  File "/Users/koder/.virtualenvs/marketapi/lib/python3.4/site-packages/pyramid/config/__init__.py", line 1073, in execute_actions
    introspectable.register(introspector, info)
  File "/Users/koder/.virtualenvs/marketapi/lib/python3.4/site-packages/pyramid/registry.py", line 220, in register
    introspector.add(self)
  File "/Users/koder/.virtualenvs/marketapi/lib/python3.4/site-packages/pyramid/registry.py", line 96, in add
    category[intr.discriminator] = intr
TypeError: unhashable type: 'AllPermissionsList'
```

**Comment by tseaver** [comment]
Can you please post a gist/link to `marketapi/__init__.py`, so that we can see what app configuration is triggering the stacktrace?  Maybe the relevant stanza from your INI file, as well?

**Comment by mmerickel** [comment]
It looks like you used ALL_PERMISSIONS somewhere that you shouldn't have. As @tseaver said can you post some relevant code in your app?

**Comment by bertjwregeer** [comment]
Is this still an issue or can we close this?

**Comment by mmerickel** [comment]
Closing due to lack of activity. If @cyprusglobe can please paste a code example we can reopen this!
