### ISSUE TITLE
"ValueError: Badly formed base64 data: Incorrect padding" when calling signed_deserialize on cookie

### ISSUE THREAD

**Issue by NucleaPeon** [Pylons/pyramid#2738]
I have my web app set up so that when a user visits the /login page, it will check to see if they have an existing session cookie. Right now I'm only at the point where I'm trying to decrypt the cookie and read back its data.

My session cookie factory in webapp.py:

    session_factory = SignedCookieSessionFactory(
        settings['session.secret'],
        cookie_name='session',
        hashalg='sha512', 
        max_age=None,
        timeout=None
    )
    config.set_session_factory(session_factory)

Users can reach the login page just fine the first time to log in. ``request.session`` attributes can be accessed fine too. However in the case of a user closing their browser and opening it back up and finding themselves at the login page, the page should check if they have their session cookie and do some stuff with the data.

I get to the point where I check if they have the cookie and try to de-serialize it, that's where I get the exception:

    cookie = request.cookies.get("session")
    if not cookie is None:
        data = signed_deserialize(cookie, request.registry.settings['session.secret'])
        with open('/tmp/cookie.log', 'a') as f:
                f.write("Cookie data: {}\n".format(data))

and that's when I get this stack trace:

    2016-08-10 18:25:53,990 ERROR [waitress][waitress] Exception when serving /login
    Traceback (most recent call last):
      File "/home/vagrant/webapp/lib/python3.4/site-packages/pyramid/session.py", line 85, in signed_deserialize
    base64.b64decode(bytes_(serialized[40:])))
      File "/home/vagrant/webapp/lib/python3.4/base64.py", line 90, in b64decode
        return binascii.a2b_base64(s)
    binascii.Error: Incorrect padding
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/vagrant/webapp/lib/python3.4/site-packages/waitress/channel.py", line 336, in service
    task.service()
      File "/home/vagrant/webapp/lib/python3.4/site-packages/waitress/task.py", line 169, in service
    self.execute()
      File "/home/vagrant/webapp/lib/python3.4/site-packages/waitress/task.py", line 388, in execute
    app_iter = self.channel.server.application(env, start_response)
      File "/home/vagrant/webapp/lib/python3.4/site-packages/pyramid/router.py", line 242, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
      File "/home/vagrant/webapp/lib/python3.4/site-packages/pyramid/router.py", line 217, in invoke_subrequest
    response = handle_request(request)
      File "/home/vagrant/webapp/lib/python3.4/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
      File "/home/vagrant/webapp/lib/python3.4/site-packages/pyramid_tm/__init__.py", line 99, in tm_tween
    reraise(*exc_info)
      File "/home/vagrant/webapp/lib/python3.4/site-packages/pyramid_tm/compat.py", line 15, in reraise
    raise value
      File "/home/vagrant/webapp/lib/python3.4/site-packages/pyramid_tm/__init__.py", line 80, in tm_tween
    response = handler(request)
      File "/home/vagrant/webapp/lib/python3.4/site-packages/pyramid/router.py", line 163, in handle_request
    response = view_callable(context, request)
      File "/home/vagrant/webapp/lib/python3.4/site-packages/pyramid/config/views.py", line 329, in attr_view
    return view(context, request)
      File "/home/vagrant/webapp/lib/python3.4/site-packages/pyramid/config/views.py", line 305, in predicate_wrapper
    return view(context, request)
      File "/home/vagrant/webapp/lib/python3.4/site-packages/pyramid/config/views.py", line 287, in _authdebug_view
    return view(context, request)
      File "/home/vagrant/webapp/lib/python3.4/site-packages/pyramid/config/views.py", line 355, in rendered_view
    result = view(context, request)
      File "/home/vagrant/webapp/lib/python3.4/site-packages/pyramid/config/views.py", line 501, in _requestonly_view
    response = view(request)
      File "/vagrant/app/company/views/webpages/home.py", line 236, in login
    data = signed_deserialize(cookie, request.registry.settings['session.secret'])
      File "/home/vagrant/webapp/lib/python3.4/site-packages/pyramid/session.py", line 88, in signed_deserialize
    raise ValueError('Badly formed base64 data: %s' % e)
    ValueError: Badly formed base64 data: Incorrect padding

The ini file secret key is 37 characters long. When I set session data, the cookie's size increases to around 3.4Kb. 

Pyramid versions:

    pyramid (1.5.7)
    pyramid-beaker (0.8)
    pyramid-debugtoolbar (2.4.2)
    pyramid-mailer (0.14.1)
    pyramid-mako (1.0.2)
    pyramid-tm (0.12)

I could not find any previous issues on your github relating to incorrect padding.

How do I get the contents out of a signed cookie of which I have all the pre-requisites for?
Thanks in advance.

**Comment by NucleaPeon** [comment]
I was playing around with the cookie string and reading up, I found a couple things:

1. The cookie string was not divisible by 4 (which is a requirement), so perhaps a correct cookie string wasn't generated. Knowing this I added two "==" signs onto the string.
2. Using ``base64.b64decode`` failed but using ``base64.urlsafe_b64decode`` worked without causing an exception.

**Comment by mmerickel** [comment]
Okay, `signed_deserialize` is not compatible with the `SignedCookieSessionFactory`. It is only used with the deprecated `UnencryptedCookieSessionFactory`.

This seems to be a side-bar however. I can't tell what your actual issue is but it seems to have more to do with the following quote. The rest of your ticket is just attempting to work around this:

> Users can reach the login page just fine the first time to log in. request.session attributes can be accessed fine too. However in the case of a user closing their browser and opening it back up and finding themselves at the login page, the page should check if they have their session cookie and do some stuff with the data.

First, if you have `max_age=None` then the cookie is a browser-session-cookie and will be gone when the user closes the browser. Second, If you want to check if they have the session cookie then just test for a value in the session:

```
if 'my_key_I_added_when_you_logged_in' in request.session:
    # session is there..
```

**Comment by mmerickel** [comment]
Closing to due no response.
