### ISSUE TITLE
HTTPFound - UnicodeEncodeError

### ISSUE THREAD

**Issue by mpekalski** [Pylons/pyramid#2771]
I have a form with which I submit fields with some unicode string. Then I process the form and return `HTTPFound`. It works if I pass only ascii characters, fails on anything more complicated, like Polish character ł.

What I tried to solve the problem is:
- setting up mako encoding to utf-8
- decoding the whole request with utf-8
```
def request_factory(environ):
    req = Request(environ)
    return req.decode(charset='utf-8')
```
- setting encoding in all my files (python and mako templates) using `# -*- coding: utf-8 -*-`
- using `request.POST[''].decode('utf-8')`
- explicitly passing `request.decode('utf-8')` to `HTTPFound`
but none of them worked.

Up until `HTTPFound` everything works fine. The function `caption_update` below gets executed and the data is getting updated in the database, but then I got the exception.

Below is my **view**, which throws the exception
```
@view_config(route_name='form_caption_edit', renderer='json', request_method='POST', require_csrf=True, check_csrf=True)
def form_caption_edit_post(request):
     log.debug('post')
     form = Form(request,
               schema = CaptionSchema())
     if form.validate(skip_csrf=True):
        log.debug('validated')
        new_caption = request.POST['new_caption']
        lang = request.POST['lang']
        file_name = request.matchdict['file_name']
        #request.session.flash('Form was submitted successfully.')
        session = request.session
        caption_update(file_name, lang, new_caption)
        log.debug('httpfound')
        log.info(request)
        return HTTPFound(request.route_url('gallery_show', request=request, _scheme='https'))
     return dict(renderer=FormRenderer(form), form_url = request.route_url('form_caption_edit', request=request, _scheme='https'))
```

**Log**
```
2016-09-23 00:09:18,495 ERROR [pyramid_debugtoolbar:209][MainThread] Exception at http://mydomain.com/caption/edit/44d42995-bfd6-473c-ab3a-eb5b6f85f66f
traceback url: http://mydomain.com/_debug_toolbar/exception?token=05b090a4332296b3f7f2&tb=140317129912528
Traceback (most recent call last):
  File "/home/mm/webapps/f/lib/python2.7/pyramid_debugtoolbar/toolbar.py", line 192, in toolbar_tween
    response = _handler(request)
  File "/home/mm/webapps/f/lib/python2.7/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/mm/webapps/f/lib/python2.7/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/mm/webapps/f/lib/python2.7/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/mm/webapps/f/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 101, in tm_tween
    reraise(*exc_info)
  File "/home/mm/webapps/f/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 83, in tm_tween
    response = handler(request)
  File "/home/mm/webapps/f/lib/python2.7/pyramid/router.py", line 158, in handle_request
    view_name
  File "/home/mm/webapps/f/lib/python2.7/pyramid/view.py", line 547, in _call_view
    response = view_callable(context, request)
  File "/home/mm/webapps/f/lib/python2.7/pyramid/config/views.py", line 182, in __call__
    return view(context, request)
  File "/home/mm/webapps/f/lib/python2.7/pyramid/viewderivers.py", line 393, in attr_view
    return view(context, request)
  File "/home/mm/webapps/f/lib/python2.7/pyramid/viewderivers.py", line 371, in predicate_wrapper
    return view(context, request)
  File "/home/mm/webapps/f/lib/python2.7/pyramid/viewderivers.py", line 354, in _authdebug_view
    return view(context, request)
  File "/home/mm/webapps/f/lib/python2.7/pyramid/viewderivers.py", line 512, in csrf_view
    return view(context, request)
  File "/home/mm/webapps/f/lib/python2.7/pyramid/viewderivers.py", line 413, in viewresult_to_response
    result = view(context, request)
  File "/home/mm/webapps/f/lib/python2.7/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/mm/webapps/f/lib/python2.7/myapp/form_caption_edit.py", line 50, in form_caption_edit_post
    return HTTPFound(request.route_url('gallery_show', request=request, _scheme='https'))
  File "/home/mm/webapps/f/lib/python2.7/pyramid/url.py", line 277, in route_url
    path = route.generate(kw) # raises KeyError if generate fails
  File "/home/mm/webapps/f/lib/python2.7/pyramid/urldispatch.py", line 234, in generator
    v = str(v)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0142' in position 2273: ordinal not in range(128)
```

**Request** that makes HTTPFound fail. It is part with data for field "new_caption".
```
2016-09-23 00:15:20,027 INFO  [myapp.form_caption_edit:49][MainThread] POST /caption/edit/b062e77b-ff23-40f6-84cc-a103d30c5dab HTTP/1.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding: gzip, deflate, lzma, br
Accept-Language: en-US,en;q=0.8
Cache-Control: max-age=0
Connection: close
Content-Length: 752
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryTOrtAmfhIs2hkjte
Cookie: auth_tkt=...!userid_type:int; auth_tkt=...!userid_type:int; session=...
Dnt: 1
Forwarded-Request-Uri: /caption/edit/b062e77b-ff23-40f6-84cc-a103d30c5dab
Host: mydomain.com
Http-X-Forwarded-Proto: https
Https: on
Origin: https://mydomain.com
Referer: https://mydomain.com/gallery_show
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36 OPR/39.0.2256.71
X-Forwarded-For: 83.251.112.78
X-Forwarded-Host: mydomain.com
X-Forwarded-Proto: https
X-Forwarded-Server: mydomain.com
X-Forwarded-Ssl: on

------WebKitFormBoundaryTOrtAmfhIs2hkjte
Content-Disposition: form-data; name="csrf_token"

593fd25120e64f6a333e6da6c29ca32d3d8b99c2
------WebKitFormBoundaryTOrtAmfhIs2hkjte
Content-Disposition: form-data; name="csrf_token"

593fd25120e64f6a333e6da6c29ca32d3d8b99c2
------WebKitFormBoundaryTOrtAmfhIs2hkjte
Content-Disposition: form-data; name="new_caption"

aaaeeełłł
------WebKitFormBoundaryTOrtAmfhIs2hkjte
Content-Disposition: form-data; name="lang"

en
------WebKitFormBoundaryTOrtAmfhIs2hkjte
Content-Disposition: form-data; name="file_name"

b062e77b-ff23-40f6-84cc-a103d30c5dab
------WebKitFormBoundaryTOrtAmfhIs2hkjte
Content-Disposition: form-data; name="submit"

Submit
------WebKitFormBoundaryTOrtAmfhIs2hkjte--


```

**Comment by bertjwregeer** [comment]
Why are you passing the `request` object to `route_url`? 

`request.route_url` explicitly calls `route_url` on the `request` object. There is no point in passing it in. Pyramid is attempting to match the keyword argument up against a replacement in your route definition, however in doing so it tries to turn it into a string. That is failing.

```
return HTTPFound(request.route_url('gallery_show', _scheme='https'))
```

Should work without issues (btw, if your WSGI environment is set up correctly you won't need to override the `_scheme` when creating URL's)

**Comment by mpekalski** [comment]
Agree. That was stupid mistake. I ported my old pylons code and changed all `route_url `to be called on request, and tried to remove all request parameters but it seems like I missed this one. 

It works now. Thanks!

A bit side question, what should I look at when setting up the WSGI environment to force https when creating URLs?

**Comment by bertjwregeer** [comment]
Waitress has some documentation on how to make sure your environment is set up correctly:

http://docs.pylonsproject.org/projects/waitress/en/latest/#passing-the-x-forwarded-proto-header-to-set-wsgi-url-scheme
