### ISSUE TITLE
pserve --reload not working in Windows

### ISSUE THREAD

**Issue by laskeym** [Pylons/pyramid#2970]
I'm currently working on the Quick Tutorials for Pyramid to get myself familiar with creating a Pyramid application:
http://docs.pylonsproject.org/projects/pyramid/en/latest/quick_tutorial/cookiecutters.html

I ran through all the commands and can successfully run my application using `%VENV%\Scripts\pserve development.ini`.  When I decide to run `%VENV%\Scripts\pserve development.ini --reload` I get the following error:

`Traceback (most recent call last):
  File "C:\Python34\Lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python34\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\mlaskey.HEALTHPLAN\wc\cc_starter\env\Scripts\pserve.exe\__main__.py", line 9, in <module>
  File "c:\users\mlaskey.healthplan\wc\cc_starter\env\lib\site-packages\pyramid\scripts\pserve.py", line 40, in main
    return command.run()
  File "c:\users\mlaskey.healthplan\wc\cc_starter\env\lib\site-packages\pyramid\scripts\pserve.py", line 205, in run
    verbose=self.args.verbose,
  File "c:\users\mlaskey.healthplan\wc\cc_starter\env\lib\site-packages\hupper\reloader.py", line 290, in start_reloader

    return reloader.run()
  File "c:\users\mlaskey.healthplan\wc\cc_starter\env\lib\site-packages\hupper\reloader.py", line 111, in run
    if not self._run_worker():
  File "c:\users\mlaskey.healthplan\wc\cc_starter\env\lib\site-packages\hupper\reloader.py", line 144, in _run_worker
    self.worker.start()
  File "c:\users\mlaskey.healthplan\wc\cc_starter\env\lib\site-packages\hupper\worker.py", line 129, in start
    os.set_inheritable(self.stdin_fd, True)
OSError: [WinError 87] The parameter is incorrect`

Has anybody encountered this problem?

**Comment by mmerickel** [comment]
Yes the issue is here https://github.com/Pylons/hupper/issues/12. It is still waiting for a fix on windows.

**Comment by laskeym** [comment]
Thank you.
