### ISSUE TITLE
Pyramid 1.9.1, pserve and ConfigParser

### ISSUE THREAD

**Issue by kalbermattenm** [Pylons/pyramid#3130]
I get some kind of strange issue using Pyramid 1.9.1 in a project on Windows 10

I have a project in which I would like to use `flake8`. If I add this one to my `setup.py` file in my pyramid app, then it installs `configparser` as a dependency (which is OK...). I used to do so in other Pyramid projects (Pyramid<1.8) and I did not encounter any issue.

But with Pyramid 1.9.1, as soon as I install `configparser`, I get the here under error.

Does anyone have any hint on what is going on ?

```
:\git_projects\sitn_portal>.build\venv\Scripts\pserve development.ini --reload
Traceback (most recent call last):
  File "c:\python27\Lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\git_projects\sitn_portal\.build\venv\Scripts\pserve.exe\__main__.py", line 9, in <module>
  File "c:\git_projects\sitn_portal\.build\venv\lib\site-packages\pyramid\scripts\pserve.py", line 32, in main
    return command.run()
  File "c:\git_projects\sitn_portal\.build\venv\lib\site-packages\pyramid\scripts\pserve.py", line 170, in run
    self.pserve_file_config(loader, global_conf=config_vars)
  File "c:\git_projects\sitn_portal\.build\venv\lib\site-packages\pyramid\scripts\pserve.py", line 133, in pserve_file_config
    settings = loader.get_settings('pserve', global_conf)
  File "c:\git_projects\sitn_portal\.build\venv\lib\site-packages\plaster_pastedeploy\__init__.py", line 72, in get_settings
    return OrderedDict(parser.items(section))
  File "c:\python27\Lib\ConfigParser.py", line 642, in items
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'pserve'
```

**Comment by kalbermattenm** [comment]
OK... I did something quite stupid which resolved this issue... I just added an empty `[pserve]` section in my `development.ini` file. Doing so resolved the issue and I was able to start `pserve` as usual.

The thing is, do not ask me why this is working and what that empty section changed...

I am closing this issue, but if anybody as a rational explanation on what just happened, I would be happy to hear about it...

**Comment by bertjwregeer** [comment]
https://github.com/Pylons/plaster_pastedeploy/issues/5

**Comment by bertjwregeer** [comment]
https://github.com/Pylons/plaster_pastedeploy/commit/8b1c376cbfebb7eccd41e0b3c75e1c08adbb6971

**Comment by kalbermattenm** [comment]
+1, thanks for the feedback @bertjwregeer
