### ISSUE TITLE
pserve development.ini --reload: fails in windows 10 64bit

### ISSUE THREAD

**Issue by mdaadil** [Pylons/pyramid#3169]
I am following [an article](http://www.brettdangerfield.com/post/creating_a_blog_with_pyramid_mongdb_bootstrap/) and creating my first project, 

while i try the below command the process gets into a loop and starts a server and kills it and again starts a server and kills and it keeps doing this continuously without breaking the loop and exiting.

pserve development.ini --reload

Below is the log
//---------------------------------------------------------
Starting monitor for PID 18084.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Others\Python\myBlog\lib\site-packages\hupper\ipc.py", line 322, in spawn_main
    func(**kwargs)
  File "D:\Others\Python\myBlog\lib\site-packages\hupper\worker.py", line 237, in worker_main
    func(*spec_args, **spec_kwargs)
  File "D:\Others\Python\myBlog\lib\site-packages\pyramid\scripts\pserve.py", line 32, in main
    return command.run()
  File "D:\Others\Python\myBlog\lib\site-packages\pyramid\scripts\pserve.py", line 229, in run
    app = loader.get_wsgi_app(app_name, config_vars)
  File "D:\Others\Python\myBlog\lib\site-packages\plaster_pastedeploy\__init__.py", line 131, in get_wsgi_app
    global_conf=defaults)
  File "d:\others\python\myblog\lib\site-packages\paste\deploy\loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "d:\others\python\myblog\lib\site-packages\paste\deploy\loadwsgi.py", line 271, in loadobj
    global_conf=global_conf)
  File "d:\others\python\myblog\lib\site-packages\paste\deploy\loadwsgi.py", line 296, in loadcontext
    global_conf=global_conf)
  File "d:\others\python\myblog\lib\site-packages\paste\deploy\loadwsgi.py", line 320, in _loadconfig
    return loader.get_context(object_type, name, global_conf)
  File "d:\others\python\myblog\lib\site-packages\paste\deploy\loadwsgi.py", line 450, in get_context
    global_additions=global_additions)
  File "d:\others\python\myblog\lib\site-packages\paste\deploy\loadwsgi.py", line 562, in _pipeline_app_context
    for name in pipeline[:-1]]
  File "d:\others\python\myblog\lib\site-packages\paste\deploy\loadwsgi.py", line 562, in <listcomp>
    for name in pipeline[:-1]]
  File "d:\others\python\myblog\lib\site-packages\paste\deploy\loadwsgi.py", line 406, in get_context
    global_conf=global_conf)
  File "d:\others\python\myblog\lib\site-packages\paste\deploy\loadwsgi.py", line 296, in loadcontext
    global_conf=global_conf)
  File "d:\others\python\myblog\lib\site-packages\paste\deploy\loadwsgi.py", line 328, in _loadegg
    return loader.get_context(object_type, name, global_conf)
  File "d:\others\python\myblog\lib\site-packages\paste\deploy\loadwsgi.py", line 620, in get_context
    object_type, name=name)
  File "d:\others\python\myblog\lib\site-packages\paste\deploy\loadwsgi.py", line 646, in find_egg_entry_point
    possible.append((entry.load(), protocol, entry.name))
  File "D:\Others\Python\myBlog\lib\site-packages\pkg_resources\__init__.py", line 2405, in load
    return self.resolve()
  File "D:\Others\Python\myBlog\lib\site-packages\pkg_resources\__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "D:\Others\Python\myBlog\lib\site-packages\weberror-0.13.1-py3.6.egg\weberror\evalexception.py", line 127
    except ValueError, ve:
                     ^
SyntaxError: invalid syntax
Killing server with PID 18084.
Starting monitor for PID 18600.
Traceback (most recent call last):

**Comment by stevepiercy** [comment]
Thanks for the report. Note that as of Pyramid 1.8, `pcreate` is deprecated, and we recommend using cookiecutters now.
https://github.com/pylons/?query=cookiecutter

We generally don't support third party (community contributed) tutorials, and that article is 5 years old. You could also contact the author of the article and the maintainer of pyramid_mongodb for additional support. We also don't support deprecated methods.

I also noticed that the author used this command to install the project:

```bash
 ../bin/python setup.py develop
```

The preferred method is to stick to one package installing tool:

```bash
 ../bin/pip install -e .
```

FWIW, I was able to replicate the error with Python 3.6.1 on macOS. This might be an issue with the weberror package. Here's how to replicate the issue.

```bash
Steves-iMac:a_mongo stevepiercy$ python -m venv env
Steves-iMac:a_mongo stevepiercy$ env/bin/pip install --upgrade setuptools pip
Steves-iMac:a_mongo stevepiercy$ env/bin/pip install pyramid_mongodb
Steves-iMac:a_mongo stevepiercy$ env/bin/pcreate -t pyramid_mongodb my_blog
Steves-iMac:a_mongo stevepiercy$ cd my_blog/
Steves-iMac:my_blog stevepiercy$ ../env/bin/pip install -e .
Steves-iMac:my_blog stevepiercy$ ../env/bin/pserve development.ini --reload
Starting monitor for PID 52398.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/stevepiercy/projects/a_mongo/env/lib/python3.6/site-packages/hupper/ipc.py", line 322, in spawn_main
    func(**kwargs)
  File "/Users/stevepiercy/projects/a_mongo/env/lib/python3.6/site-packages/hupper/worker.py", line 237, in worker_main
    func(*spec_args, **spec_kwargs)
  File "/Users/stevepiercy/projects/a_mongo/env/lib/python3.6/site-packages/pyramid/scripts/pserve.py", line 32, in main
    return command.run()
  File "/Users/stevepiercy/projects/a_mongo/env/lib/python3.6/site-packages/pyramid/scripts/pserve.py", line 229, in run
    app = loader.get_wsgi_app(app_name, config_vars)
  File "/Users/stevepiercy/projects/a_mongo/env/lib/python3.6/site-packages/plaster_pastedeploy/__init__.py", line 131, in get_wsgi_app
    global_conf=defaults)
  File "/Users/stevepiercy/projects/a_mongo/env/lib/python3.6/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/Users/stevepiercy/projects/a_mongo/env/lib/python3.6/site-packages/paste/deploy/loadwsgi.py", line 271, in loadobj
    global_conf=global_conf)
  File "/Users/stevepiercy/projects/a_mongo/env/lib/python3.6/site-packages/paste/deploy/loadwsgi.py", line 296, in loadcontext
    global_conf=global_conf)
  File "/Users/stevepiercy/projects/a_mongo/env/lib/python3.6/site-packages/paste/deploy/loadwsgi.py", line 320, in _loadconfig
    return loader.get_context(object_type, name, global_conf)
  File "/Users/stevepiercy/projects/a_mongo/env/lib/python3.6/site-packages/paste/deploy/loadwsgi.py", line 450, in get_context
    global_additions=global_additions)
  File "/Users/stevepiercy/projects/a_mongo/env/lib/python3.6/site-packages/paste/deploy/loadwsgi.py", line 562, in _pipeline_app_context
    for name in pipeline[:-1]]
  File "/Users/stevepiercy/projects/a_mongo/env/lib/python3.6/site-packages/paste/deploy/loadwsgi.py", line 562, in <listcomp>
    for name in pipeline[:-1]]
  File "/Users/stevepiercy/projects/a_mongo/env/lib/python3.6/site-packages/paste/deploy/loadwsgi.py", line 406, in get_context
    global_conf=global_conf)
  File "/Users/stevepiercy/projects/a_mongo/env/lib/python3.6/site-packages/paste/deploy/loadwsgi.py", line 296, in loadcontext
    global_conf=global_conf)
  File "/Users/stevepiercy/projects/a_mongo/env/lib/python3.6/site-packages/paste/deploy/loadwsgi.py", line 328, in _loadegg
    return loader.get_context(object_type, name, global_conf)
  File "/Users/stevepiercy/projects/a_mongo/env/lib/python3.6/site-packages/paste/deploy/loadwsgi.py", line 620, in get_context
    object_type, name=name)
  File "/Users/stevepiercy/projects/a_mongo/env/lib/python3.6/site-packages/paste/deploy/loadwsgi.py", line 646, in find_egg_entry_point
    possible.append((entry.load(), protocol, entry.name))
  File "/Users/stevepiercy/projects/a_mongo/env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2405, in load
    return self.resolve()
  File "/Users/stevepiercy/projects/a_mongo/env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/stevepiercy/projects/a_mongo/env/lib/python3.6/site-packages/weberror/evalexception.py", line 127
    except ValueError, ve:
                     ^
SyntaxError: invalid syntax
Server with PID 52398 exited with code 1.
Waiting for changes before reloading.
```

Finally please visit the [official and supported tutorials](https://docs.pylonsproject.org/projects/pyramid_tutorials/en/latest/) in the Pyramid repository should you want to continue learning Pyramid.

**Comment by bertjwregeer** [comment]
`weberror` is not supported on Python 3, and likely never will. Removing it from your stack will likely allow `pserve` to start.
