### ISSUE TITLE
upgrade 1.8 -> 1.9 won't start.

### ISSUE THREAD

**Issue by kgk** [Pylons/pyramid#3191]
We tend to use .cfg instead of .ini which used to work.  Is this broken on purpose ?
Renaming cfg -> ini doesn't seem to have an effect.

Thanks,
Kris 

```
pserve -v config/h1_pserve.cfg 
Traceback (most recent call last):
  File "/home/kgk/Envs/bq06new/bin/pserve", line 11, in <module>
    sys.exit(main())
  File "/home/kgk/Envs/bq06new/local/lib/python2.7/site-packages/pyramid/scripts/pserve.py", line 32, in main
    return command.run()
  File "/home/kgk/Envs/bq06new/local/lib/python2.7/site-packages/pyramid/scripts/pserve.py", line 167, in run
    loader = self._get_config_loader(config_uri)
  File "/home/kgk/Envs/bq06new/local/lib/python2.7/site-packages/pyramid/scripts/common.py", line 23, in get_config_loader
    return plaster.get_loader(config_uri, protocols=['wsgi'])
  File "/home/kgk/Envs/bq06new/local/lib/python2.7/site-packages/plaster/loaders.py", line 109, in get_loader
    raise LoaderNotFound(requested_scheme, protocols=protocols)
plaster.exceptions.LoaderNotFound: Could not find a matching loader for the scheme "file+cfg", protocol "wsgi".

```

**Comment by tseaver** [comment]
Pyramid 1.9 moved to using [plaster](http://plaster.readthedocs.io/en/latest/) to load config files.  Is your `.cfg` file one which matches the standard INI format used for Paste?  If so, renaming it to `.ini` *should* cause the loader to be found.

Rather than renaming it, you might try passing the URI scheme explicitly:

```bash
$ pserve -v file+ini:config/h1_pserve.cfg
```

**Comment by kgk** [comment]
that  works for me.  Thanks.

**Comment by mmerickel** [comment]
Thank you @tseaver!

@kgk I would have expected renaming your file to `config/h1_pserve.ini` to work. Does it not?

**Comment by kgk** [comment]
We had several places that we would need to change.. plus the team is very used to work with site.cfg, logging.cfg etc.. It was easier change the code to force the protocol than try renaming/retraining.
