### ISSUE TITLE
pyramid.scripting.get_root() triggers AttributeError 

### ISSUE THREAD

**Issue by hathawsh** [Pylons/pyramid#3262]
In Pyramid 1.9.1, get_root() triggers an AttributeError on threadlocal_manager:

```
# bin/pshell mything/development.ini 
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help" for more information.

Environment:
  app          The WSGI application.
  registry     Active Pyramid registry.
  request      Active request object.
  root         Root of the default resource tree.
  root_factory Default root factory used to create `root`.

>>> from pyramid.scripting import get_root
>>> x = get_root(app)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/shane/src/pyramidtest/eggs/pyramid-1.9.1-py3.5.egg/pyramid/scripting.py", line 30, in get_root
    app.threadlocal_manager.push(threadlocals)
AttributeError: 'Router' object has no attribute 'threadlocal_manager'
>>>
```

**Comment by mmerickel** [comment]
Just released 1.9.2 with this fix. Thanks for the report.
