### ISSUE TITLE
Test failures with Pyramid 1.10a1

### ISSUE THREAD

**Issue by fschulze** [Pylons/pyramid#3392]
With Pyramid 1.10a1 I get a traceback in Pyramid when running devpi-web tests. They look like this:

```python traceback
Traceback (most recent call last):
  File "/Users/fschulze/Development/devpi/devel/web/tests/test_views_misc.py", line 294, in test_status_macros_mixed
    result = statusview(None, dummyrequest)
  File "/Users/fschulze/Development/devpi/devel/web/.tox/py27/lib/python2.7/site-packages/pyramid/config/views.py", line 188, in attr_view
    return view(context, request)
  File "/Users/fschulze/Development/devpi/devel/web/.tox/py27/lib/python2.7/site-packages/pyramid/config/views.py", line 208, in predicate_wrapper
    if not predicate(context, request):
  File "/Users/fschulze/Development/devpi/devel/web/.tox/py27/lib/python2.7/site-packages/pyramid/predicates.py", line 155, in __call__
    return bool(request.accept.acceptable_offers(self.values))
AttributeError: 'str' object has no attribute 'acceptable_offers'
```

I guess they are related to #3326

**Comment by mmerickel** [comment]
@fschulze thanks for the report and trying the alpha.

The issue is that the accept predicate used to do `value in request.accept` which worked on the string you are setting on the dummy request [1] but webob deprecated this api and we are now using the new api which is `bool(request.accept.acceptable_offers([value]))`. The way to fix this is to use `request.accept = webob.acceptparse.create_accept_header('text/html')` on the dummy request. I will try to update the changelog about this better but the good news is that this should only affect your test suite and not any production code as it's an issue with the dummy request.

[1] https://github.com/devpi/devpi/blob/98bb0cdad7104e9f327e1289743530176b31a440/web/tests/test_views_misc.py#L194

**Comment by bertjwregeer** [comment]
WebOb's accept has never just been a string. I am a huge -1 to support it just for dummy objects. Maybe this is something we can help with, but use a real WebOb Request, they are cheap.

**Comment by mmerickel** [comment]
I think it's responsible to keep the DummyRequest compatible with Pyramid's new contract so I've opened #3396 to fix this. Thanks @fschulze and let me know if this doesn't fix things.

**Comment by bertjwregeer** [comment]
:+1:
